window.__WORKS__ = [
  {
    title: "1",
    year: "",
    size: "30×40 cm",
    edition: "Edition of 30",
    price: "€220",
    paymentLink: "https://buy.stripe.com/NOT_AVAILABLE_YET",
    src: "/assets/img/prints/1.jpg",
    alt: "1 — black-and-white photograph",
    description: "",
  },
  {
    title: "2",
    year: "",
    size: "30×40 cm",
    edition: "Edition of 30",
    price: "€220",
    paymentLink: "https://buy.stripe.com/NOT_AVAILABLE_YET",
    src: "/assets/img/prints/2.jpg",
    alt: "2 — black-and-white photograph",
    description: "",
  },
  {
    title: "3",
    year: "",
    size: "30×40 cm",
    edition: "Edition of 30",
    price: "€220",
    paymentLink: "https://buy.stripe.com/NOT_AVAILABLE_YET",
    src: "/assets/img/prints/3.jpg",
    alt: "3 — black-and-white photograph",
    description: "",
  },
  {
    title: "4",
    year: "",
    size: "30×40 cm",
    edition: "Edition of 30",
    price: "€220",
    paymentLink: "https://buy.stripe.com/NOT_AVAILABLE_YET",
    src: "/assets/img/prints/4.jpg",
    alt: "4 — black-and-white photograph",
    description: "",
  }
];
